pipeline {
    
    agent any
    environment{
        DOCKERHUB_USER = "mahmudulrm"
        APP_NAME = "gitops-argo-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
        IMAGE_NAME = "${DOCKERHUB_USER}" + "/" + "${APP_NAME}"
        REGISTRY_CREDS = 'dockerhub'
        // add - manage jenkins > credentials > system > global credentials - add credentials
        // git hub access personal token
    }
    stages {
        stages("Cleanup workspace"){
            steps{
                script{
                    cleanWs()
                }
            }
        }
        stages("checkout SCM"){
            steps{
                script{
                    git credentialsId: 'github'
                    url: https://github.com/vikash-kumar01/Jenkins-Docker-Project.git
                    branch: main   
                }
            }
        }
//plugins for docker (docker pipline, dashboard view) 
        stages("Docker build Image"){
            steps{
                script{
                    docker_image = docker.build "${IMAGE_NAME}"
                }
            }
        }
    }
}