pipeline {
    
    agent any
    environment{
        DOCKERHUB_USER = "mahmudulrm"
        APP_NAME = "gitops-argo-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
        IMAGE_NAME = "${DOCKERHUB_USER}" + "/" + "${APP_NAME}"
        REGISTRY_CREDS = 'dockerhub'
        // add - manage jenkins > credentials > system > global credentials - add credentials
        // git hub access personal token
    }
    stages {
        stages("Cleanup workspace"){
            steps{
                script{
                    cleanWs()
                }
            }
        }
        stages("checkout SCM"){
            steps{
                script{
                    git credentialsId: 'github'
                    url: https://github.com/vikash-kumar01/Jenkins-Docker-Project.git
                    branch: main   
                }
            }
        }
//plugins for docker (docker pipline, dashboard view) 
        stages("Docker build Image"){
            steps{
                script{
                    docker_image = docker.build "${IMAGE_NAME}"
                }
            }
        }
// install docker on jenkins server
        stages("Docker push Image"){
            steps{
                script{
                    docker.withRegistry('', REGISTRY_CREDS){
                        docker_image.push("$BUILD_NUMBER")
                        docker_image.push('latest')
                    }
                }
            }
        }
        stages("Docker Image remove"){
            steps{
                script{
                        sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG}"
                        sh "docker rmi ${IMAGE_NAME}:latest"
                    }
                }
            }
        }
        stages("update image tag in deployment yml"){
            steps{
                script{
                        sh """
                        cat deployment.yml
                        sed -i 's/${IMAGE_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' deployment.yml
                        cat deployment.yml
                        """
                    }
                }
            }
        }
                stages("git push change to git"){
            steps{
                script{
                    sh """
                      git config --global user.name "mahmudulrm"
                      git config --global user.email "mahmudulrm@gmail.com"
                      git add deployment.yml
                      git commit -m "updated the deployment file"
                    """
                    withCredentials([gitUsernamePassword(credentialsId: 'github', gitToolName: 'Default')]) {
                        
                    sh "git push https://github.com/mahmudulrm/gitops_argocd_project.git main"
                    }
                }
            }
        }
    }
}